import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Blog() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Building</title>
                <meta name="description" content="Generated by Darshan"/>
                <link rel="icon" href="/hammer.ico"/>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Under Construction
                </h1>
            </main>
        </div>
    )
}