import Head from "next/head";
import Container from "../components/Container";

export default function Blog() {
    return (
        <Container
            title={`Blog – Darshan Hindocha`}
            description={"Blog by Darshan Hindocha"}
        >
            <Head>
                <title>Building</title>
                <meta name="description" content="Generated by Darshan"/>
                <link rel="icon" href="/hammer.ico"/>
            </Head>
            <main className="flex flex-col items-center justify-around w-full max-w-2xl mx-auto mb-16">
                <h1 className="mb-4 text-3xl font-bold tracking-tight text-black md:text-5xl dark:text-white">
                    Under Construction
                </h1>
            </main>
        </Container>
    )
}