import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import {useRouter} from "next/router";

const Home: NextPage = () => {
    const router = useRouter();


    return (
        <div className={styles.container}>
            <Head>
                <title>Darshan Hindocha</title>
                <meta name="description" content="Generated by Darshan"/>
                <link rel="icon" href="/hammer.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Hello!
                </h1>

                <p className={styles.description}>
                    I am under construction at the moment.
                </p>
                <p>Here is a test post for now</p>

                <Button
                    variant="contained"
                    onClick={() => {
                        router.push({pathname: '/blog/test'})
                    }}
                >
                    Test Post
                </Button>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
